// src/api/dummyCourses.js

const imageURL = 'https://cdn.pixabay.com/photo/2025/06/11/22/12/kackar-mountains-9655201_1280.jpg';

export const dummyCourses = [
  {
    id: 1,
    title: "Full Stack Web Development",
    description: "Build responsive, dynamic websites using HTML, CSS, JS, React, Node.js, and MongoDB.",
    instructor: "Ishita Sharma",
    price: 1499,
    rating: 4.7,
    duration: "12 Weeks",
    level: "Intermediate",
    image: imageURL,
    category: "Web Development",
  },
  {
    id: 2,
    title: "Cyber Security Fundamentals",
    description: "Explore ethical hacking, network security, encryption, and Indian cyber laws.",
    instructor: "Ravi Menon",
    price: 999,
    rating: 4.5,
    duration: "8 Weeks",
    level: "Beginner",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnKAoWYCN06QFU7vD1_xpLgRhpn-BLGzSVUg&s",
    category: "Cyber Security",
  },
  {
    id: 3,
    title: "Data Science with Python",
    description: "Learn data analysis, visualization, and machine learning using Python, NumPy, and pandas.",
    instructor: "Dr. Meera Kapoor",
    price: 1299,
    rating: 4.8,
    duration: "10 Weeks",
    level: "Intermediate",
    image: imageURL,
    category: "Data Science",
  },
  {
    id: 4,
    title: "Digital Marketing Essentials",
    description: "Master SEO, Google Ads, social media marketing, and brand positioning strategies.",
    instructor: "Kunal Rajput",
    price: 899,
    rating: 4.4,
    duration: "6 Weeks",
    level: "Beginner",
    image: imageURL,
    category: "Marketing",
  },
  {
    id: 5,
    title: "UI/UX Design Bootcamp",
    description: "Learn wireframing, prototyping, and design systems with Figma and Adobe XD.",
    instructor: "Ananya Desai",
    price: 1099,
    rating: 4.6,
    duration: "7 Weeks",
    level: "All Levels",
    image: imageURL,
    category: "Design",
  },
  {
    id: 6,
    title: "Mobile App Development",
    description: "Build native and cross-platform mobile apps using Flutter and Dart.",
    instructor: "Rajesh Patel",
    price: 1399,
    rating: 4.7,
    duration: "9 Weeks",
    level: "Intermediate",
    image: imageURL,
    category: "Mobile Development",
  },
  {
    id: 7,
    title: "MERN Stack Projects",
    description: "Hands-on full-stack projects with MongoDB, Express, React, and Node.js.",
    instructor: "Sanya Gupta",
    price: 1599,
    rating: 4.9,
    duration: "6 Weeks",
    level: "Advanced",
    image: imageURL,
    category: "Full Stack",
  }
];
